blog_nature/urls.py
from django.urls import path


from .views import *
app_name = 'nature'
urlpatterns = [

    path('', NatureView, name='nature'),
    path('new', NatureCreateView.as_view(), name='new'),
    path("<int:product_id>/delete", nature_delete, name='delete'),
    path("<int:nature_id>/update", nature_update, name='update'),

    path('<str:nature_name>/category', CategoryNatureView.as_view(), name='nature_category'),
    path('like/',like_post , name='like-post')
    ]

blog_oku/urls.py
from django.urls import path
from .views import *


app_name = 'okuu'
urlpatterns = [

    path('',BlogView.as_view(),name='learn_view'),
    path('new/', OkuCreateView.as_view(), name='oku_new'),
    path('<int:pk>/edit/', ArticleUpdateView.as_view(), name="article_edit"),
    path("<int:bloglearn_id>/delete", blog_learn_delete, name='bloglearn_delete'),
    path("<int:bloglearn_id>/detail", BlogDetail.as_view(), name='learn_detail'),
    # comments url
    path("<int:bloglearn_id>/comment/new", learn_comment, name='blog_comment_new'),
    path("<int:bloglearn_id>/comment/<int:comment_id>/delete", delete_learn_comment, name='comment_delete'),
    # end comments url
    # test url
    path('list/',testlist,name='list_test'),
    path('<int:test_id>/ready_to_test',ready_to_test,name="ready_to_test"),
    path('<int:test_id>/test',test,name="test"),
    path('<int:checktest_id>/checktest',checktest,name='checktest'),
    path('new_test',new_test,name='new_test'),
    path('<int:test_id>/new_question',new_question,name='new_question'),
    # category url
    path('<str:oku_name>/category', CategoryLearnView.as_view(), name='oku_category'),
    path('test/<str:category_name>/category', TestView.as_view(), name='category'),
    # end category
    # like button url
    path('like-oku/', like_oku, name='like-oku'),
    path('like/', like_learn_detail, name='like-detail'),
    path('like_test/', like_test, name='like-test'),
    path('like_liki/', like_learn_comment, name='like_learn_comment'),
    # end like button url
]

chat/urls.py
from . import views
from django.urls import path

from .views import *
app_name = 'chat'
urlpatterns = [
    path('chat/<str:username>', chat, name="chat"),
    path('data/<str:username>', data, name="data"),
    path('', friends, name='haus'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from config.views import home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('store/', include('store.urls')),
                  path('oku/', include('blog_oku.urls')),
                  path('chats/', include('chat.urls')),
                  path('blog_admin/', include('blog_admin.urls')),
                  path('blog_nature/', include('blog_nature.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *



app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='shop'),
    path("<int:product_id>/detail/", product_detail, name='detail'),
    path("new", new_product, name='new'),
    path("<int:product_id>/update", product_updat, name='update'),
    path("<int:product_id>/delete", product_delete, name='delete'),
    # comments
    path("<int:product_id>/comment/new", new_comment, name='comment_new'),
    path("<int:product_id>/comment/<int:comment_id>/delete", delete_comment, name='comment_delete'),
    #like button url
    path('like/', like_store, name='like-store'),
    path('like_store/', like_store_comment, name='like_comment'),
    # category
    path('<str:category_name>/category', CategoryView.as_view(), name='category'),
    # book


]

templates/include/add_button.html
{% load grouptags%}


{% url 'adminn' as admin_page_url %}
{% url 'okuu:learn_view' as learn_page_url%}
{% url 'haus' as message_page_url %}
{% url 'main:shop' as stor_page_url%}
{% url 'nature:nature' as nature_page_url%}
{% url 'okuu:list_test' as test_page_url%}

<style>

  .mb{
  margin-bottom:5rem;}


.fabs {
  position: fixed;
  right: 30px;
  bottom: 20px;
}

.action {
  background: rgb(255, 0, 128);
  height: 50px;
  width: 50px;
  border-radius: 50%;
  transition: background-color 0.4s ease-in-out;
}

.action i {
  position: absolute;
  color: white;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  font-size: 25px;
  cursor: pointer;
}

.action:hover {
  background-color: rgb(255, 103, 179);
}



</style>
  <body>
    <div class="fabs mb" onclick="toggleBtn()">
      <div class="action">


         {% if request.path == admin_page_url %}
              <a href="{%url 'article_new'%}">
                {% endif %}

                 {% if request.path == stor_page_url%}
               <a href="{%url 'main:new'%}">
            {% endif %}
                {% if request.path == learn_page_url%}
                 <a href="{%url 'okuu:oku_new'%}">
            {% endif %}
                {% if request.path == nature_page_url%}
                <a href="{%url 'nature:new'%}">
            {% endif %}

                 {% if request.path == test_page_url %}
                 <a href="{% url 'okuu:new_test'%}">
                {% endif %}


        <i class="bi bi-plus-lg"></i></i>
        <i class="fas fa-times" id="remove" style="display: none"></i>
              </a>
      </div>
    </div>

  </body>
  <script>
    function toggleBtn() {
      const Btns = document.querySelector(".btns");
      const add = document.getElementById("add");
      const remove = document.getElementById("remove");
      const btnnn = document.querySelector(".btns").querySelectorAll("a");
      Btns.classList.toggle("open");
      if (Btns.classList.contains("open")) {
        remove.style.display = "block";
        add.style.display = "none";
        btnnn.forEach((e, i) => {
          setTimeout(() => {
            bottom = 70 * i;
            e.style.bottom = bottom + "px";
            console.log(e);
          }, 100 * i);
        });
      } else {
        add.style.display = "block";
        remove.style.display = "none";
        btnnn.forEach((e, i) => {
          e.style.bottom = "0px";
        });
      }
    }
  </script>

templates/include/all_modal.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          Lorem Ipsum - это текст-"рыба", часто используемый в печати и вэб-дизайне. Lorem Ipsum является стандартной "рыбой" для текстов на латинице с начала XVI века. В то время некий безымянный печатник создал большую коллекцию размеров и форм шрифтов, используя Lorem Ipsum для распечатки образцов. Lorem Ipsum не только успешно пережил без
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- nature -->
<div class="modal fade" id="nature" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        бул болум стрестен арулу учун иштелип чыкан бул жерде сиз кыргызстандын жана дуйнонун эн кооз жерлерин корсонуз болот
        --эгер сиздеда ушундай видео же суротор болсо ушул болумго чыгырун каласаныздар бизгеге арыз жонотун---
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">рахмат тушундум</button>
        <button type="button" class="btn btn-primary">арыз жонотуу</button>
      </div>
    </div>
  </div>
</div>

<!-- learnadd -->
<div class="modal fade" id="learnadd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- store add -->
<div class="modal fade" id="storeadd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- admin blog -->
<div class="modal fade" id="blogadmin" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        бул болумдо сиз аркандай кесиптин элери жана студенттер андан тышкары университеттер жонундо малымат ала аласыздыр
        <hr>эгер сизда бир кесиптин эси болуп оз тажрыбаныз менен болушуну каласаныз арыз жонотун
        ---сиз посторду сактап койсонуз болот __
        __ой пикирлер жана кемчиликтер болсо биз менен байланышып толук жооп алууга болот--
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">тушундум</button>
        <button type="button" class="btn btn-primary">арыз жонуту</button>
      </div>
    </div>
  </div>
</div>
<!-- admin add -->
<div class="modal fade" id="adminadd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- bloglearn -->
<div class="modal fade" id="bloglearn" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        бул болумдо сиз оз суроолорунуз постко чыгыарып жооп алсаныз болот же болбосо билген суронуз менен жооп берин --
        андар сырткары тест болумуго отсонуз болот--
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- natureadd -->
<div class="modal fade" id="natureadd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- testlist -->
<div class="modal fade" id="testlist" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- home -->
<div class="modal fade" id="home" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">M'sycamore</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          бул платформа балдарда билим алуу мумкунчулугун жакшыртуу учун иштелип чыкты ю
        сиз бул жерде кыйналган сууронуз беришиниз жан билсениз башкалар жардам беришиниз мумкун андан тышкары стрестен арулу дуконбжан жана аркандай малыматарды алышыныз мумкун
        !толук малымат арбир болумго койулган ? ушуну басып била алас

        !бирон кемситу же аркандай жаман создорду пайдалануга толук тыйу салынат
        жана ескетусуз акаунту очурулот
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>