accounts/urls.py
from django.urls import path
from .views import *
app_name = 'users'
urlpatterns = [
    path('register', SignupView.as_view(), name='register'),
    path("login/", Login.as_view(), name="login"),
    path('profile/<str:username>', ProfailView.as_view(), name='profile'),
    path('update/', UpdateProfileView.as_view(), name='update'),
    # saved product
    path('addremovesaved/<int:product_id>', AddRemoveSavedView.as_view(), name='addremovesaved'),
    path('saveds',SavedView.as_view(),name='saveds'),
    # saved nature
    path('savedsnature/<int:nature_id>', NatureSavedView.as_view(), name='naturesaved'),
    path('savedstest/<int:test_id>', TestSavedView.as_view(), name='test_saved'),
    path('savedsadmin/<int:admin_id>', AdminSavedView.as_view(), name='adminsaved'),
    path('savedslearn/<int:bloglearn_id>', LearnSavedView.as_view(), name='learnsaved'),
    path('recently_viewed',RecentlyViewedView.as_view(),name='recently_viewed'),
    path('logout/',logout_user,name='logout'),
    path('contact',contactForm,name='contact_form'),
    path('discover/', discover, name='discover'),

]

blog_oku/urls.py
from django.urls import path
from .views import *


app_name = 'okuu'
urlpatterns = [

    path('',BlogView.as_view(),name='learn_view'),
    path('new/', OkuCreateView.as_view(), name='oku_new'),
    path('<int:pk>/edit/', ArticleUpdateView.as_view(), name="article_edit"),
    path("<int:bloglearn_id>/delete", blog_learn_delete, name='bloglearn_delete'),
    path("<int:bloglearn_id>/detail", BlogDetail.as_view(), name='learn_detail'),
    # comments url
    path("<int:bloglearn_id>/comment/new", learn_comment, name='blog_comment_new'),
    path("<int:bloglearn_id>/comment/<int:comment_id>/delete", delete_learn_comment, name='comment_delete'),
    # end comments url
    # test url
    path('list/',testlist,name='list_test'),
    path('<int:test_id>/ready_to_test',ready_to_test,name="ready_to_test"),
    path('<int:test_id>/test',test,name="test"),
    path('<int:checktest_id>/checktest',checktest,name='checktest'),
    path('new_test',new_test,name='new_test'),
    path('<int:test_id>/new_question',new_question,name='new_question'),
    # category url
    path('<str:oku_name>/category', CategoryLearnView.as_view(), name='oku_category'),
    path('test/<str:category_name>/category', TestView.as_view(), name='category'),
    # end category
    # like button url
    path('like-oku/', like_oku, name='like-oku'),
    path('like/', like_learn_detail, name='like-detail'),
    path('like_test/', like_test, name='like-test'),
    path('like_liki/', like_learn_comment, name='like_learn_comment'),
    # end like button url
]

chat/urls.py
from . import views
from django.urls import path

from .views import *
app_name = 'chat'
urlpatterns = [
    path('chat/<str:username>', chat, name="chat"),
    path('data/<str:username>', data, name="data"),
    path('', friends, name='haus'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from config.views import home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('store/', include('store.urls')),
                  path('oku/', include('blog_oku.urls')),
                  path('chats/', include('chat.urls')),
                  path('blog_admin/', include('blog_admin.urls')),
                  path('blog_nature/', include('blog_nature.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_oku/forms.py
from django import forms

from blog_oku.models import Test, Question, BlogLearnComment


class EdirCommentForm(forms.ModelForm):
    class Meta:
        model = BlogLearnComment
        fields = ( 'body',)

class CommentModelForm(forms.ModelForm):
    #model = BlogLearnComment
    #fields = ['body']
    body = forms.CharField(label='',
                           widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))

    class Meta:
        model = BlogLearnComment
        fields = ('body',)


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ('title','category','maximum_attemps','start_date',"end_date",'pass_percentage')
        labels = {
            "title":" тестин аты",
            'category':"болум",
            "maximum_attemps":"колдонучу канча жолу арекет кылса болот",
            'start_date':"качан башталсын",
            "end_date":"качан бутсун",
            'pass_percentage':"канча просенттен ашса тестен откон болуп эсептелсин",
        }

    def save(self,request,commit=True):
        test = self.instance
        test.author = request.user
        super().save(commit)
        return test.id

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question','a','b','c','d','true_answer')
        labels = {
           "question":"суроо",
            "true_answer":"туура жооп" ,
            "submit_and_exit":"g",
        }

    болот_жетишту = forms.BooleanField(required=False)

    def save(self,test_id,commit=True):
        question = self.instance
        question.test = Test.objects.get(id=test_id)
        super().save(commit)
        return question

blog_oku/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, UpdateView
from blog_oku.forms import TestForm, QuestionForm, EdirCommentForm, CommentModelForm
from blog_oku.models import BlogLearn, BlogLearnComment, Test, Question, CheckQuestion, CheckTest, LearnCategory, \
    TestCategory, LikeOku, LikeLearn, LikeTest


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = BlogLearn
    fields = ('description','category')
    template_name = 'blog_oku/blog_oku_edit.html'
    success_url = reverse_lazy('okuu:learn_view')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class OkuCreateView(LoginRequiredMixin,UserPassesTestMixin, CreateView):
    model = BlogLearn
    template_name = 'blog_oku/blog_oku_add.html'
    fields = ('category',"object_category",'image','description',)
    success_url = reverse_lazy('okuu:learn_view')#м

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    def test_func(self):
        return self.request.user

class BlogView(LoginRequiredMixin,View):
    def get(self, request,):

        bloglearn = BlogLearn.objects.all()
        q = request.GET.get('q',)
        if q:
            bloglearn = bloglearn.filter(description__icontains=q, )

        context = {
            'bloglearn': bloglearn,

        }

        return render(request, "blog_oku/blog_oku.html", context)


class BlogDetail(LoginRequiredMixin,View):
    def get(self, request, bloglearn_id):
        bloglearn = get_object_or_404(BlogLearn, id=bloglearn_id)
        comments = bloglearn.comments.filter(active=True)
        comment_count = comments.count()
        context = {
            'bloglearn': bloglearn,
            'comment_count': comment_count,
            'comments': comments
        }

        return render(request, 'blog_oku/blog_learn_detail.html', context)



@login_required(login_url='users:login')
def blog_learn_delete(request, bloglearn_id):
    bloglearn = get_object_or_404(BlogLearn, id=bloglearn_id)
    if request.user == bloglearn.author:
        if request.method == 'POST':
            bloglearn.delete()
            messages.info(request, 'Successfully Deleted!')
            return redirect('okuu:learn_view')
        return render(request, "blog_oku/blog_oku_delete.html", {'bloglearn': bloglearn})
    else:
        messages.error(request, 'Access danied!')
        return redirect('okuu:learn_view')



# create comments

@login_required(login_url='users:login')
def learn_comment(request, bloglearn_id):
    bloglearn = get_object_or_404(BlogLearn, id=bloglearn_id)
    if request.method == 'POST':
        BlogLearnComment.objects.create(
            author=request.user,
            bloglearn=bloglearn,
            body=request.POST['body']
        )

        messages.info(request, 'Successfully send comment!')
        return redirect('okuu:learn_detail', bloglearn_id)
    return HttpResponse('add comment')




@login_required(login_url='users:login')
def delete_learn_comment(request, bloglearn_id, comment_id, *args, **kwargs):
    comment = get_object_or_404(BlogLearnComment, id=comment_id)
    if request.user == comment.author:
        comment.delete()
        messages.info(request, 'Successfully delete comment!')
        return redirect('okuu:learn_detail', bloglearn_id)
    return redirect('okuu:learn_detail', bloglearn_id)


#end create comments
# test create

class TestView(LoginRequiredMixin,View):
    def get(self, request, category_name):
        category = get_object_or_404(TestCategory, name=category_name)
        products = Test.objects.filter(category=category)
        q = request.GET.get('q', '')
        if q:
            products = products.filter(title__icontains=q)
        return render(request, "blog_oku/test/test_list.html", {'tests': products, "category": category})


@login_required(login_url='users:login')
def testlist(request):
    tests = Test.objects.all()
    q = request.GET.get('q', '')
    if q:
        tests = tests.filter(title__icontains=q)
    return render(request,'blog_oku/test/test_list.html' , {'tests': tests})#'blog_oku/test_list.html'


@login_required(login_url='login')
def ready_to_test(request, test_id):  # теске дайар
    test = get_object_or_404(Test, id=test_id)
    return render(request, 'blog_oku/test/ready_to_test.html', {'test': test})


@login_required(login_url='users:login')
def test(request, test_id):
    test = get_object_or_404(Test, id=test_id)
    attemps = CheckTest.objects.filter(student=request.user, test=test).count()
    if (timezone.now() >= test.start_date and timezone.now() <= test.end_date) and attemps < test.maximum_attemps:
        questions = Question.objects.filter(test=test)
        if request.method == 'POST':
            checktest = CheckTest.objects.create(student=request.user, test=test)
            for question in questions:
                given_answer = request.POST[str(question.id)]
                CheckQuestion.objects.create(checktest=checktest, question=question, given_answer=given_answer,
                                             true_answer=question.true_answer)
            checktest.save()
            return redirect('okuu:checktest', checktest.id)
        context = {'test': test, 'questions': questions}
        return render(request, 'blog_oku/test/test.html', context)
    else:
        return HttpResponse('test not Found!')


@login_required(login_url='users:login')
def checktest(request, checktest_id):
    checktest = get_object_or_404(CheckTest, id=checktest_id, student=request.user)
    return render(request, 'blog_oku/test/checktest.html', {'checktest': checktest})

#add question

@login_required(login_url='users:login')
def new_test(request):
    form = TestForm()
    if request.method=='POST':
        form = TestForm(data=request.POST)
        if form.is_valid:
            test_id = form.save(request)
            return redirect('okuu:new_question',test_id)
    return render(request,'blog_oku/test/new_test.html',{'form':form})

@login_required(login_url='users:login')
def new_question(request,test_id):
    test = get_object_or_404(Test,id=test_id)
    if test.author == request.user:
        form = QuestionForm()
        if request.method == 'POST':
            form = QuestionForm(data=request.POST)
            if form.is_valid:
                form.save(test_id)
                if form.cleaned_data['болот_жетишту']:
                    return redirect('okuu:list_test')     #okuu:index
                return redirect('okuu:new_question',test.id)
        return render(request,'blog_oku/test/new_question.html',{'form':form,'test':test})
    else:
        return HttpResponse('something went wrong')
#end add question


#category
def for_all_pages_oku(request):
    categories = LearnCategory.objects.all()
    return {"learn_category": categories}


class CategoryLearnView(LoginRequiredMixin,View):
    def get(self, request, oku_name):
        category = get_object_or_404(LearnCategory, name=oku_name)
        bloglearn = BlogLearn.objects.filter(category=category)
        q = request.GET.get('q', '')
        if q:
            bloglearn = bloglearn.filter(title__icontains=q)
        return render(request, "blog_oku/test/blog_oku.html", {'bloglearn': bloglearn, "category": category})

def for_all_pages_test(request):
    categories = TestCategory.objects.all()
    return {"test_category": categories}

#end category
# create like button

@login_required(login_url='users:login')
def like_learn_comment(request ,):
    user = request.user
    if request.method =='POST':
        post_id = request.POST.get('post_id')
        post_obj = BlogLearnComment.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = LikeLearn.objects.get_or_create(user=user ,post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect(request.META.get('HTTP_REFERER'))


@login_required(login_url='users:login')
def like_learn_detail(request ,):
    user = request.user
    if request.method =='POST':
        post_id = request.POST.get('pos_id')
        post_obj = BlogLearn.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = LikeOku.objects.get_or_create(user=user ,post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='users:login')
def like_test(request ,):
    user = request.user
    if request.method =='POST':
        post_id = request.POST.get('post_id')
        post_obj = Test.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = LikeTest.objects.get_or_create(user=user ,post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect('okuu:list_test',)


@login_required(login_url='users:login')
def like_oku(request ,):

templates/blog_oku/blog_comment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col"></div>
        <div class="col-10 mt-5 ">
            <h2>ondoo</h2>
              <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">сактоо</button>
                 {# <a class="btn btn-danger" href="{% url 'article_delete' object.id  %}"> Delete</a>#}
    </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/blog_oku/blog_learn_detail.html
{%extends 'base.html'%}
{% load static %}
{% block content %}

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />

  <!-- MDB icon -->

  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <!-- MDB --
  <link rel="stylesheet" href="css/bootstrap-comments.min.css" />-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'css/readbutton.css'%}">
</head>

<body>

 <section >
    <div class="container my-3 py-5">
      <div class="row d-flex justify-content-center">
        <div class="col-md-12 col-lg-10 col-xl-8">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-start align-items-center">
                <img class="rounded-circle shadow-1-strong me-3"
                  src="{{request.user.pic.url}}" alt="avatar" width="35"
                  height="35" />

                    <div>
                  <h6 class="fs-6 mb-1 badge bg-success me-5">#{{bloglearn.category}}</h6>

                        <!-- delete button-->
                        {% if request.user == bloglearn.author %}
                      <a href="{% url 'okuu:bloglearn_delete' bloglearn.id %}" class="link-muted me-4"><i class="bi bi-trash3"></i></i></a>
				 <a class="btn "  href="{% url 'okuu:article_edit' bloglearn.id%}">
				  <i class="bi bi-pen"></i>
			  	</a>
				  {% endif %}

                <!-- end button delete-->
                  <p class="text-muted small mb-0 me-5">
                    {{bloglearn.date}}
                  </p>
                </div>


              </div>
              <div class="img-wrap">
                {% if bloglearn.image %}
				 <img class="card-img-top" src="{{bloglearn.image.url}}"
                  />
                  {% endif %}


			</div> <!-- img-wrap.// -->
              <p class="mt-3 mb-4 pb-2">
              {{bloglearn.description}}
              </p>

              <div class="small d-flex justify-content-start">
                <a href="#!" class="d-flex align-items-center me-3">
                  <p class="mb-0 me-3"><i class="far fa-comment-dots me-1"> жооптор:</i> {{bloglearn.comments.count}}</p>
                </a>

                <a  class="d-flex align-items-center me-3"href="{% url 'okuu:learn_view'%}">
                  <i class="fas fa-share me-2"></i>
                  <p class="mb-0">артка кайтуу</p>
                </a>
              </div>
            </div>


               <form action="{% url 'okuu:blog_comment_new' bloglearn.id %}" method="post" class="input-group">{% csrf_token%}
          <input class="form-control" name="body" type="text" placeholder="сиздин жооп ..." aria-describedby="'button-addon" >
          <button class="btn btn-outline-success" type="submit" id="button-addon"> жоноту <i class="bi bi-send-plus"></i></button>
      </form>
          </div>

          {% for comment in comments %}
          <div class="card mt-3">


            <div class=" card-body">

              <div class="w-100">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h6 class="text-primary fw-bold mb-0">
                    <a href="{% url 'users:profile' comment.author.username  %}">@{{comment.author}}</a>

                  </h6>
                  <p class="mb-0">{{comment.date}}</p>
                </div>

                <div data-expandable>
                  <p>{{comment.body}} </p>
                {#  <button data-expand-button class=" btn btn-primary btn-sm">Read More</button>#}
                  <div class="d-flex justify-content-between align-items-center mt-3">
                    <div class="d-flex align-items-center">

                         <form action="{% url 'okuu:like_learn_comment' %}" method="POST" class='like-form' id='{{comment.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{comment.id}}>

                            <button type="submit" class="btn-sm btn btn-outline-success  like-btn{{comment.id}}">
                                {% if user not in comment.liked.all %}
                                    Like
                                {% else %}
                                     Unlike
                                {% endif %}
                            </button>
                             <strong class=" me-4 like-count{{comment.id}}"> {{comment.num_likes}}</strong>
                    </form>
                    </div>
                     {% if request.user == comment.author %}
                        <small ><a class="link-delete" href="{% url 'okuu:comment_delete' bloglearn.id comment.id   %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="24" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg></a>
                        </small>
                    {% endif %}
                  </div>

                </div>

              </div>

            </div>
          </div>

        {% endfor%}
        </div>
      </div>
    </div>
  </section>
  <!-- Start your project here-->
<script src="{% static 'js/like_button.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="{% static 'js/readbutton.js'%}"></script>
</body>

{% endblock content %}

templates/blog_oku/blog_oku.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<head>
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" />
  <!-- MDB --
  <link rel="stylesheet" href="css/bootstrap-comments.min.css" />-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>



  <!-- Start your project here-->
<section  class="top bottom" style="">
  <div class="container mt-5"> <!-- my-5 py-5-->
    <div class="row d-flex justify-content-center">
      <div class="col-md-12 col-lg-10">
          {% for i in bloglearn %}
        <div class="card mt-3">
          <div class="card-body ">
                 <div class="d-flex align-items-center mb-0">
                      <img class="rounded-circle shadow-1-strong me-2"
                src="{{i.author.pic.url}}" alt="avatar" width="30"
                height="30" />
                     <h6 class="fs-6 mb-1 badge bg-info me-1">#{{i.category}}</h6><h6 class="fs-6 mb-1 badge bg-success me-2">#{{i.object_category}}</h6>

                 </div>
                <div class="d-flex align-items-center mb-3">
                  <p class="mb-0 me-4">
                    {{i.date}}
                  </p>
                     {% if request.user == i.author %}
                  <a href="{% url 'okuu:article_edit' i.id%}" class="link-muted me-4"><i class="fas fa-pencil-alt ms-2"></i></a>
                  <a href="{% url 'okuu:bloglearn_delete' i.id %}" class="link-muted me-4"><i class="bi bi-trash3"></i></i></a>
                    {% endif%}
                      {% if  i.image %}
                  <a href="#!" class="link-muted"><i class="bi bi-images"></i></a>
                    {% endif %}
                </div>
                <p class="mb-0 font-monospace">
                  {{i.description}}
                </p>
              <div class="d-flex justify-content-between align-items-center mt-3">
                  <div class="d-flex align-items-center">
                      <form action="{% url 'okuu:like-oku'%}" method="POST" class='like-form' id='{{i.id}} '>
                              {% csrf_token %}

                                <input type="hidden" name="post_id" value={{i.id}}>
                                    <button type="submit" class="btn btn-outline-success btn-sm like-btn{{i.id}}">
                                        {% if user not in i.liked.all %}
                                            Like
                                        {% else %}
                                            Unlike
                                        {% endif %}
                                    </button>
                                     <strong class="like-count{{i.id}} me-5">{{i.num_likes}}</strong>

                            </form>
                    <a href="{% url 'okuu:learn_detail' i.id%}" class=" me-2"><i class="far fa-comment-dots me-1"></i>{{i.comments.count}}</a>

                  </div>
                  <a href="{% url 'okuu:learn_detail' i.id%}" class="btn btn-outline-primary btn-sm" data-mdb-ripple-color="dark"> жооп беруу</a>

                             <a href="{% url 'users:learnsaved' i.id %}" >
                               <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                                  <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                                </svg>
                             </a>


                </div>
              </div>
          </div>{% endfor%}
      </div>
    </div>
  </div>
</section>


{% include 'include/add_button.html'%}

  <!-- End your project here-->

  <script src="{% static 'js/like_button.js'%}"></script>
{% endblock content %}

templates/blog_oku/blog_oku_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container bottom top">
    <div class="row">
        <div class="col"></div>

        <div class="col-10 mt-5 ">

           <div class="row">
               <h2 class="col-10">New Post</h2>
            <button type="button" class="btn btn-info col-2" data-bs-toggle="modal" data-bs-target="#learnadd">
                      <i class="bi bi-question-lg"></i>
            </button>
           </div>

             <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <button class="btn btn-success ml-2 me-3" type="submit">сактоо</button>
                  <a  class="" href="{% url 'okuu:learn_view' %}"> back </a>
    </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/blog_oku/blog_oku_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col"></div>
            <div class="col-10 mt-5 ">
                <h1>постту очуру</h1>
                <form action="" method="post">{% csrf_token %}
                <p>"Are you sure to delete"?</p>
                <button class="btn btn-danger ml-2" type="submit">оба</button>
                     <a  class="btn btn-primary" href="{% url 'okuu:learn_view' %}"> жок </a>
                </form>
            </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/blog_oku/blog_oku_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container mb-5">
    <div class="row">
        <div class="col"></div>
        <div class="col-10 mt-5 ">
            <h2>постуу тузотуу</h2>
              <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">сактоо</button>
                   <a  href="{% url 'okuu:learn_view' %}">  артка кайтуу</a>
    </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}