accounts/urls.py
from django.urls import path
from .views import *
app_name = 'users'
urlpatterns = [
    path('register', SignupView.as_view(), name='register'),
    path("login/", Login.as_view(), name="login"),
    path('profile/<str:username>', ProfailView.as_view(), name='profile'),
    path('update/', UpdateProfileView.as_view(), name='update'),
    # saved product
    path('addremovesaved/<int:product_id>', AddRemoveSavedView.as_view(), name='addremovesaved'),
    path('saveds',SavedView.as_view(),name='saveds'),
    # saved nature
    path('savedsnature/<int:nature_id>', NatureSavedView.as_view(), name='naturesaved'),
    path('savedstest/<int:test_id>', TestSavedView.as_view(), name='test_saved'),
    path('savedsadmin/<int:admin_id>', AdminSavedView.as_view(), name='adminsaved'),
    path('savedslearn/<int:bloglearn_id>', LearnSavedView.as_view(), name='learnsaved'),
    path('recently_viewed',RecentlyViewedView.as_view(),name='recently_viewed'),
    path('logout/',logout_user,name='logout'),
    path('contact',contactForm,name='contact_form'),
    path('discover/', discover, name='discover'),

]

blog_nature/urls.py
from django.urls import path


from .views import *
app_name = 'nature'
urlpatterns = [

    path('', NatureView, name='nature'),
    path('new', NatureCreateView.as_view(), name='new'),
    path("<int:product_id>/delete", nature_delete, name='delete'),
    path("<int:nature_id>/update", nature_update, name='update'),

    path('<str:nature_name>/category', CategoryNatureView.as_view(), name='nature_category'),
    path('like/',like_post , name='like-post')
    ]

chat/urls.py
from . import views
from django.urls import path

from .views import *
app_name = 'chat'
urlpatterns = [
    path('chat/<str:username>', chat, name="chat"),
    path('data/<str:username>', data, name="data"),
    path('', friends, name='haus'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from config.views import home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('store/', include('store.urls')),
                  path('oku/', include('blog_oku.urls')),
                  path('chats/', include('chat.urls')),
                  path('blog_admin/', include('blog_admin.urls')),
                  path('blog_nature/', include('blog_nature.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models

# Create your models here.
from accounts.models import CustomUser


class Chat(models.Model):
    sender = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='receiver')
    chat = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    is_seen = models.CharField(default="&#10003;", max_length=150)


    def __str__(self):
        return str(self.sender) + ' >>> ' + str(self.receiver)

chat/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render

from accounts.models import Friend, CustomUser
from .models import Chat
from django.shortcuts import get_object_or_404
@login_required(login_url='users:login')
def chat(request, username):
    receiver = CustomUser.objects.get(username=username)
    user = request.user
    friends = set(Friend.objects.filter(user=user))
    friend = CustomUser.objects.filter(username__in=friends)

    # Send massage
    if request.method == "POST":
        massage = request.POST['massage']
        chat = Chat(chat=massage, sender=user, receiver=receiver)
        chat.save()
        try:
            Friend.objects.get(user=user, friend=receiver)
        except Friend.DoesNotExist:
            Friend.objects.create(user=user, friend=receiver)
            Friend.objects.create(user=receiver, friend=user)

    # List of Friends
    for f in friend:
        unread = Chat.objects.filter(sender=f, receiver=user, is_seen="&#10003;").count()
        fr = Friend.objects.filter(user=user, friend=f)
        fr.update(unread=unread)

    return render(request, 'chat/chat.html', {'receiver': receiver, 'friends': friends})


@login_required(login_url='users:login')
def data(request, username):
    receiver = CustomUser.objects.get(username=username)
    sender = user = request.user
    massages = Chat.objects.filter(
        Q(receiver=receiver, sender=sender) | Q(receiver=sender, sender=receiver)
    ).order_by("id")
    Chat.objects.filter(sender=receiver, is_seen="&#10003;").update(is_seen="&#10003; &#10003;")
    # Equilize unred to 0 when user see the massages

    fr = Friend.objects.filter(user=user, friend=receiver)
    fr.update(unread=0)
    return JsonResponse({"massages": list(massages.values())})


@login_required(login_url='users:login')
def friends(request):
    user = request.user
    friends = set(Friend.objects.filter(user=user))
    friend = CustomUser.objects.filter(username__in=friends)
    for f in friend:
        unread = Chat.objects.filter(sender=f, receiver=user, is_seen="&#10003;").count()
        fr = Friend.objects.filter(user=user, friend=f)
        fr.update(unread=unread)
    return render(request, 'chat/home_chat.html', {'friends': friends})

templates/chat/chat.html
{% extends 'chat/chat_base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
<style>
    row {
    width: auto !important;
    }
    h6{    margin-bottom: 0rem !important;}
</style>
 <div class="chat">
                <div class="chat-header clearfix">
                    <div class="row">
                        <div class="col-lg-6 me-5">

                            <a href="" data-toggle="modal" data-target="#view_info">
                                {% if receiver.pic %}
                                <img src="{{receiver.pic.url}}" alt="avatar">
                                {% endif %}
                            </a>
                            <div class="chat-about">
                                <h6 class="m-b-0">{{receiver.username}}</h6>
                                <small>Last seen: {{receiver.last_login|naturaltime}}</small>
                            </div>
                            <div class="col-lg-6 hidden-sm text-right">
                            <a style="float: right ; width:50px" href="{%url 'chat:haus'%}" class="btn btn-outline-secondary"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M160 416H96c-17.67 0-32-14.33-32-32V128c0-17.67 14.33-32 32-32h64c17.67 0 32-14.33 32-32S177.7 32 160 32H96C42.98 32 0 74.98 0 128v256c0 53.02 42.98 96 96 96h64c17.67 0 32-14.33 32-32S177.7 416 160 416zM502.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L402.8 224H192C174.3 224 160 238.3 160 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C515.1 266.1 515.1 245.9 502.6 233.4z"/></svg></a>

                            <div style="clear: both ;" ></div>

                        </div>

                        </div>
                    </div>
                </div>
                <div id="a"   style="height:530px; overflow:auto; background-image: url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTdkzg8iVEiqBXM7Xlgfh34KO0J28F8WIDQ&usqp=CAU);" class="chat-history">
                    <div id="display">
                   </div>

                   <br><br>
                   <div id="focus"></div>
                </div>
                <div class="chat-message clearfix">
                  <form  id="post-form" method="POST", action="{% url 'chat:chat' user.username%}" >{% csrf_token %}
                    <div class="input-group mb-0">

                        <input required name="massage" id="massage" type="text" class="form-control" placeholder="Enter text here...">
                         <div class="input-group-prepend">
                             <button type="submit" ><span class="input-group-text btn-info"><i class="bi bi-send-plus"></i></span></button>
                        </div>
                    </div>
                  </form>
                </div>
            </div>



<script>

   $( "#a" ).scrollTop(9999)
    $(document).ready(function(){
        setInterval(function(){
            $.ajax({
                type: 'GET',
                url : "/chats/data/{{receiver}}",
                success: function(response){
                    $("#display").empty();
                    for (var key in response.massages){
                        if ("{{request.user.id}}" == response.massages[key].sender_id)
                           var temp = ('<div class="my-massages"  data-bs-toggle="tooltip" data-bs-placement="top" title="'+response.massages[key].time +' " ><p class="text" >' + response.massages[key].chat +   '</p><p class="time"  >'+ response.massages[key].is_seen + ' </p></div><div class="clr" ></div>')
                        else
                            // var temp = "<li>"+response.massages[key].chat + " to " + "{{receiver}}" + " </li>";
                            var temp = ('<div class="other-massages" data-bs-toggle="tooltip" data-bs-placement="top" title="'+response.massages[key].time + ' " ><p class="text" >'+ response.massages[key].chat +  '</p><p class="time"  > </p></div><div class="clr" ></div>')

                            $("#display").append(temp);


                    }
                },
                error: function(response){
                    alert(" An error occured")
                },
            });
        },1000)

    });


    $(document).on('submit', '#post-form', function test(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            data : {
                massage:$('#massage').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(data){
                $('#post-form')[0].reset()
                $( "#a" ).scrollTop(9999)
            },
        });
    });

</script>

{% endblock content%}

templates/chat/chat_base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
      <link rel="stylesheet" href="{% static 'css/chat.css' %}">

</head>
<body class="container" >


<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card chat-app">
            <div id="plist" class="people-list">
                {% if user.is_authenticated %}
                <ul class="list-unstyled chat-list mt-2 mb-0">
                    <li class="clearfix"><a style="color: black ; text-decoration:none; " href="/profile/{{user.username}}" >

                        {% if user.pic %}
                        <img  src="{{user.pic.url}}" alt="avatar">
                        {% else %}
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAV4KeX1dWGctJDMu6xo3GS7cDEhjk1nlZ5A&usqp=CAU" alt="avatar">
                        {% endif %}
                        <div class="about">
                        <div style="margin-top: 10px;" class="name"><strong>{{user.first_name}} {{user.last_name}} </strong></div></a>


                </li>
             <hr>


                  {% for f in friends %}
                     <div class="friends"><li class="clearfix"><a href="{% url 'chat:chat' f.friend.username%}" >{% if f.friend.pic %}<img  src="{{f.friend.pic.url}}" alt="avatar">{% else %}<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAV4KeX1dWGctJDMu6xo3GS7cDEhjk1nlZ5A&usqp=CAU" alt="avatar">
                            {% endif %}

                            <div class="about">


                            <div class="name">{{f.friend.first_name}} {{f.friend.last_name}}
                                {% if f.unread %}
                                <span class="position-absolute translate-middle badge rounded-pill bg-danger">
                                    {{ f.unread }}
                                    <span class="visually-hidden">unread messages</span>
                                  </span>
                                {% endif %}
                            </div>
                            <div class="status"> <i class="fa fa-circle offline"></i>   {{f.friend.last_login|naturaltime}} </div>
                            </div></a>

                    </li>
                </div>
                  {% endfor %}
                </ul>
                {% else %}<br><br>
                <p class="text-muted"> You are not authenticated</p>
                {% endif %}
            </div>
           {% block content %}
           {% endblock content %}
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/chat/discover.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/secondary.css' %}">
<body class=" m-3 border-0 bd-example">

    <!-- Example Code -->
    <div class=" d-flex justify-content-center mt-5">
        {% if user.is_authenticated %}
    <div class="col-md-8 col-lg-6">
        <h1 class="mt-4 linda"><a href="{% url 'chat:haus'%}" class=" ml-0 me-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="30" fill="currentColor" class="bi bi-arrow-left-square-fill" viewBox="0 0 16 16">
  <path d="M16 14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12zm-4.5-6.5H5.707l2.147-2.146a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708-.708L5.707 8.5H11.5a.5.5 0 0 0 0-1z"/>
</svg>
        </a>  Discover friends</h1>
             <div class="linda" >
                      <form  class=" input-group mb-3 mt-3" style="width: 350px;" method="get" >
                      <input name="q" type="search" class="form-control" placeholder="Search global friends" aria-label="Recipient's username" aria-describedby="button-addon2">
                      <button   class="btn btn-outline-secondary" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                        </svg></i></button>
                      </form>
                </div>
        {% for user in users %}
        <div class="card mb-3 " style="margin-left:1rem;">
          <div class="card-body">
                <a href="{% url 'chat:chat' user.username%}" >
                <div class="d-flex flex-start">
                {% if user.pic %}
                <img  class="rounded-circle shadow-1-strong me-3" src="{{user.pic.url}}" alt="avatar"width="30" height="30" />
                        {% endif %}
              <div class="w-100">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h6 class="text-primary fw-bold mb-0">
                      {{user.username}}

                  </h6>

                  <p class="status mb-0"> <i class="fa fa-circle offline"></i> {{user.last_login|naturaltime}}</p>
                </div>
              </div>

            </div>
                </a>
          </div>
        </div>


{% endfor %}
    </div>

  </div>

    </div>
         {% else %}<br><br>
                <p class="text-muted"> You are not authenticated</p>
                {% endif %}
    </div>

    <!-- End Example Code -->

  </body>
{% endblock content %}

templates/chat/home_chat.html
{% extends 'base.html'%}
{% load static %}
{% load humanize %}
{% block content %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
  <body class=" m-0 border-0 bd-example">

    <!-- Example Code -->
    <div class="row d-flex justify-content-center mt-5">
        {% if user.is_authenticated %}
    <div class="col-md-8 col-lg-6 mt-3">
        <div class="card-body">
            <a style="float: right ; width:40px" href="{% url 'users:discover'%}" class="btn btn-outline-secondary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
            </svg></i>
            </a>
            <h1>Discover friends</h1>
        </div>

 {% for f in friends %}

            <div class="card mb-3 mt-3">
          <div class="card-body">
                <a href="{% url 'chat:chat' f.friend.username%}" >
            <div class="d-flex flex-start">
                {% if f.friend.pic %}
                        <img class="rounded-circle shadow-1-strong me-3" src="{{ f.friend.pic.url}}" alt="avatar" width="30"
                height="30" />
                        {% endif %}
                <div class="w-100">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h6 class="text-primary fw-bold mb-0">
                    {{f.friend.username}}
                       {% if f.unread %}
                                <span class="position-absolute translate-middle badge rounded-pill bg-danger">
                                    {{ f.unread }}
                                    <span class="visually-hidden">unread messages</span>
                                  </span>
                      {% endif %}
                  </h6>
                  <p class="status mb-0"> <i class="fa fa-circle offline"></i> {{f.friend.last_login|naturaltime}}</p>
                </div>
              </div>

            </div>
                </a>
          </div>
        </div>



{% endfor %}
    </div>

  </div>

    </div>
         {% else %}<br><br>
                <p class="text-muted"> You are not authenticated</p>
                {% endif %}
    </div>

    <!-- End Example Code -->

  </body>
{% endblock content %}

templates/chat/links.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/secondary.css' %}">

  </head>
  <body>
    {% block content %}
    {% endblock content %}






    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

<link rel="stylesheet" href="{% static 'css/admin.css'%}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'css/readbutton.css'%}">

<div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                     {% for nature in products %}
                    <div class="card mb-3" style="margin-left:2.5rem">
                         {% if nature.image %}
                        <img class="d-block w-100 " width="400" height="270" src="{{nature.image.url}}" alt="">
                         {% endif%}
                        {% if nature.video %}
                            <video class="embed-responsive embed-responsive-16by9" controls="controls">
                                <source src="{{nature.video.url}}" type="video/mp4" />
                            </video>
                        {% endif%}
                        <div class="d-flex flex-start align-items-center mt-0 bot">
                            <img class="rounded-circle shadow-1-strong me-1 mr-0"
                                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="28" height="28" />
                            <div class="lko">
                                <p class="mb-0">
                                    <a class="mb-0 mt-0 font-monospace small fs-6 " style="color:#fff;" href="{% url 'users:profile' nature.author.username  %}">@{{nature.author}}
                                        <span class="small"> <i class="bi bi-calendar-check"></i> {{ nature.date|date:'Y-m-d'}}</span>
                                    </a>
                                </p>

                                <p class=" small mb-0 mt-0" style="color:#fff;">
                                    {% if request.user == nature.author %}
                                    <a class="btn topricht" href="{% url 'nature:update' nature.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff"
                                            class=" float-end bi bi-three-dots-vertical" viewBox="0 0 16 16">
                                            <path
                                                d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                                        </svg>
                                    </a>
                                    {% endif %}
                                </p>
                            </div>
                        </div>

                    <div>
                        <div class="d-flex justify-content-start">
                             <p class="me-5 mb- m-1" style="color:green;"><i class="bi bi-geo-alt-fill"></i> {{nature.address}}</p>
                                <form action="{% url 'nature:like-post' %}" method="POST" class='like-form ' id='{{nature.id}}'>
                                {% csrf_token %}

                                <input type="hidden" name="post_id" value={{nature.id}}>
                                    <button type="submit" class=" btn btn-outline-success btn-sm like-btn{{nature.id}}">
                                        {% if user  not in nature.liked.all %}
                                            Like
                                        {% else %}
                                            Unlike
                                        {% endif %}
                                    </button>
                                     <strong class="like-count{{nature.id}} me-3">{{nature.num_likes}}</strong>

                            </form>
                            <a href="{% url 'users:naturesaved' nature.id %}" class="float-end"><i class="bi bi-bookmark-fill"></i></a>

                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>


<div class="container mt-3 mb-5">
    {% for article in almanadmin %}
	<div class="card ">
		<div class="card__header">
			{% if article.photo %}
			<img src="{{ article.photo.url }}" alt="card__image" class="card__image"  width="600">
            {%  endif %}

			 <div class="card-img-top">
				  {% if request.user == article.author %}
				 <a class="btn topricht" href="{% url 'article_edit' article.id%}">
				  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#fff" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
				 <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
				</svg>
			  	</a>
				  {% endif %}
  			</div>
		</div>
		<div class="card__body">
			<span class="tag tag-blue ">{{article.category}}</span><small>  {{ article.date|date:'Y-m-d' }}</small>
			<h4 style="margin-bottom:0rem;">{{ article.title }}</h4>

			<p style="margin-bottom: 0rem;">{{ article.body }}</p>
		</div>
		<div class="  card__footer">
			<div class="user">
				<img src="https://i.pravatar.cc/40?img=1" alt="user__image" class="user__image">
				<div class="user__info me-5">
					<h6 style="
                      position: absolute;
                      bottom: 1rem;
                      left: 4rem;
                      font-size: 15px;
                    ">
						<a href="{% url 'users:profile' article.author.username  %}">@{{article.author}}</a></h6>
				</div>

				<div>
					<form action="{% url 'like-postt'%}" method="POST" class='like-form' id='{{article.id}} ' style="
                      position: absolute;
                      bottom: 0.7rem;
                      right: 1rem;
                      font-size: 15px;">
                              {% csrf_token %}

                                <input type="hidden" name="post_id" value={{article.id}}>
                                    <button type="submit" class="btn btn-outline-success btn-sm like-btn{{article.id}}">
                                        {% if user not in article.liked.all %}
                                            Like
                                        {% else %}
                                            Unlike
                                        {% endif %}
                                    </button>
                                     <strong class="like-count{{article.id}} me-3">{{article.num_likes}}</strong>
									<span>
										<a href="{% url 'users:adminsaved' article.id %}" ><i class="bi bi-bookmark"></i></a>
									</span>

                            </form>



			</div>
		</div>
	</div>

	{% endfor %}

</div>
</div>

{% include 'include/add_button.html'%}
<script src="{% static 'js/like_button.js'%}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>