accounts/urls.py
from django.urls import path
from .views import *
app_name = 'users'
urlpatterns = [
    path('register', SignupView.as_view(), name='register'),
    path("login/", Login.as_view(), name="login"),
    path('profile/<str:username>', ProfailView.as_view(), name='profile'),
    path('update/', UpdateProfileView.as_view(), name='update'),
    # saved product
    path('addremovesaved/<int:product_id>', AddRemoveSavedView.as_view(), name='addremovesaved'),
    path('saveds',SavedView.as_view(),name='saveds'),
    # saved nature
    path('savedsnature/<int:nature_id>', NatureSavedView.as_view(), name='naturesaved'),
    path('savedstest/<int:test_id>', TestSavedView.as_view(), name='test_saved'),
    path('savedsadmin/<int:admin_id>', AdminSavedView.as_view(), name='adminsaved'),
    path('savedslearn/<int:bloglearn_id>', LearnSavedView.as_view(), name='learnsaved'),
    path('recently_viewed',RecentlyViewedView.as_view(),name='recently_viewed'),
    path('logout/',logout_user,name='logout'),
    path('contact',contactForm,name='contact_form'),
    path('discover/', discover, name='discover'),

]

chat/urls.py
from . import views
from django.urls import path

from .views import *
app_name = 'chat'
urlpatterns = [
    path('chat/<str:username>', chat, name="chat"),
    path('data/<str:username>', data, name="data"),
    path('', friends, name='haus'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from config.views import home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  path('store/', include('store.urls')),
                  path('oku/', include('blog_oku.urls')),
                  path('chats/', include('chat.urls')),
                  path('blog_admin/', include('blog_admin.urls')),
                  path('blog_nature/', include('blog_nature.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *



app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='shop'),
    path("<int:product_id>/detail/", product_detail, name='detail'),
    path("new", new_product, name='new'),
    path("<int:product_id>/update", product_updat, name='update'),
    path("<int:product_id>/delete", product_delete, name='delete'),
    # comments
    path("<int:product_id>/comment/new", new_comment, name='comment_new'),
    path("<int:product_id>/comment/<int:comment_id>/delete", delete_comment, name='comment_delete'),
    #like button url
    path('like/', like_store, name='like-store'),
    path('like_store/', like_store_comment, name='like_comment'),
    # category
    path('<str:category_name>/category', CategoryView.as_view(), name='category'),
    # book


]

store/models.py
from django.db import models
from accounts.models import CustomUser
class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class BookLanguage(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    language = models.ForeignKey(BookLanguage, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=100,blank=True,  null=True)
    price = models.IntegerField(blank=True,  null=True)

    book_author = models.CharField(max_length=100, blank=True, )
    pdf = models.FileField(upload_to='books/pdfs/',blank=True,  null=True)
    date = models.DateTimeField(auto_now_add=True)
    liked = models.ManyToManyField(CustomUser, default=None, blank=True, related_name='like_store')

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ('-id',)

    @property
    def num_likes(self):
        return self.liked.all().count()



LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class LikeStore(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Product, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='like', max_length=10)

    def __str__(self):
        return str(self.post)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')




# comment
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    body = models.CharField(max_length=150)
    date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)
    liked = models.ManyToManyField(CustomUser, default=None, blank=True, related_name='like_store_comment')

    def __str__(self):
        return "Comment of " + str(self.author.username)

    @property
    def num_likes(self):
        return self.liked.all().count()


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class LikeStoreComment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Comment, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='like', max_length=10)

store/forms.py
from .models import Product
from django import forms


class NewProductForm(forms.ModelForm):
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Product
        fields = ( 'category','title',"description",'book_author','pdf', 'price', "language")
        labels = {'category':'болум',
                  'title':' китептин аты',
                  "description":'китеп жонундо малымат жазыныз',
                  'book_author':"Китептин авторлор:",
                  'price':"Басы:(эгер бекер болсо жазу шарт эмес)",
                  "language":"китеп жазылган тил",
                  "images":"суротору",
        }


    def save(self, request, commit=True):
        product = self.instance
        product.author = request.user
        super().save(commit)
        return product


class ProductForm(forms.ModelForm):
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Product
        fields = ('category','title', 'price','book_author', 'pdf',)
        labels = {'category': 'болум',
                  'title': ' китеп жонундо кичине малымат',
                  "description": 'китеп жонундо малымат',
                  'book_author': "китептин автору",
                  'price': "басы эгер бекер болсо жазуу шарт эмес",
                  "images": "суротору",
                  }

store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.shortcuts import render, redirect

from accounts.models import Saved
from .forms import NewProductForm, ProductForm
from .models import ProductImage, Product, Comment, LikeStore, LikeStoreComment, Category
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views import View
from django.shortcuts import get_object_or_404


# Create your views here.


class IndexView(LoginRequiredMixin,View):
    def get(self, request):
        products = Product.objects.all()
        q = request.GET.get('q', '')
        if q:
            products = products.filter(Q(title__icontains=q)|Q(book_author__icontains=q))

        return render(request, "store/store.html", {'products': products,})

@login_required(login_url='users:login')
#@allowed_groups(['loki',])
def new_product(request):
    if request.method == "GET":
        form = NewProductForm()
        for f in form:
            if f.label == "Images":
                f.label = "китептин суротору"


        return render(request, 'store/product_new.html', {'form': form})
    elif request.method == "POST":
        form = NewProductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            product = form.save(request)
            productimages = []
            for image in request.FILES.getlist("images"):
                ProductImage.objects.create(image=image, product=product)

            messages.success(request, "Successfully Created!")
            return redirect('main:shop')
        return render(request, 'store/product_new.html', {'form': form})

@login_required(login_url='users:login')
def product_updat(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user == product.author:
        if request.method == 'GET':
            form = ProductForm(instance=product)
            for f in form:
                if f.label == "Images":
                    f.label = "китептин суротору"

            return render(request, 'store/product_update.html', {'form': form, 'pr': product})
        elif request.method == 'POST':
            form = ProductForm(instance=product, data=request.POST, files=request.FILES)
            if form.is_valid():
                form.save()
                if request.FILES.getlist('images'):
                    ProductImage.objects.filter(product=product).delete()
                    productimages = []
                    for image in request.FILES.getlist("images"):
                        productimages.append(ProductImage(image=image, product=product))
                    ProductImage.objects.bulk_create(
                        productimages
                    )
                messages.success(request, 'Successfully Updated!')
                return redirect('main:detail', product.id)
            return render(request, 'store/product_update.html', {'form': form, 'pr': product})
    else:
        messages.error(request, 'Access danied!')
        return redirect('main:shop')

@login_required(login_url='users:login')
def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    comments = product.comments.filter(active=True)
    comment_count = comments.count()
    context = {
        'product': product,
        'comment_count': comment_count,
        'comments': comments
    }

    if "recently_viewed" in request.session:
        r_viewed = request.session["recently_viewed"]
        if not product.id in r_viewed:
            r_viewed.append(product.id)
            request.session.modified = True
    else:
        request.session["recently_viewed"] = [product.id, ]
    return render(request, 'store/product_detail.html', context)

@login_required(login_url='users:login')
def product_delete(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user == product.author:
        if request.method == 'POST':
            product.delete()
            messages.info(request, 'Successfully Deleted!')
            return redirect('main:shop')
        return render(request, "store/product_delete.html", {'product': product})
    else:
        messages.error(request, 'Access danied!')
        return redirect('main:shop')

@login_required(login_url='users:login')
def new_comment(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        Comment.objects.create(
            author=request.user,
            product=product,
            body=request.POST['body']
        )

        messages.info(request, 'Successfully send comment!')
        return redirect('main:detail', product_id)
    return HttpResponse('add comment')

@login_required(login_url='users:login')
def delete_comment(request, product_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.author:
        comment.delete()
        messages.info(request, 'Successfully delete comment!')
        return redirect('main:detail', product_id)
    return redirect('main:detail', product_id)

# category
def for_all_pages(request):
    categories = Category.objects.all()
    return {"categories": categories}

class CategoryView(View):
    def get(self, request, category_name):
        category = get_object_or_404(Category, name=category_name)
        products = Product.objects.filter(category=category)
        q = request.GET.get('q', '')
        if q:
            products = products.filter(title__icontains=q)
        return render(request, "store/store.html", {'products': products, "category": category})

# end category

# like buttons
@login_required(login_url='users:login')
def like_store(request, ):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Product.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = LikeStore.objects.get_or_create(user=user, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect('main:shop')

@login_required(login_url='users:login')
def like_store_comment(request, ):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Comment.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = LikeStoreComment.objects.get_or_create(user=user, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()

    return redirect(request.META.get('HTTP_REFERER'))

templates/store/product_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-sm-12 col-md-12 col-lg-6  mt-5 ">
            <h2>Are you sure to delete -  {{product.title}}</h2>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}

                <button type="submit" class="btn btn-primary" >Submit</button>
               <a class="btn btn-secondary" href="{% url 'main:detail' product.id %}"> Back </a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/store/product_detail.html
{%extends 'base.html'%}
{% load static%}
{% block content%}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
	  xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="{%static 'css/store.css'%}"}>
<link rel="stylesheet" href="{%static 'css/store_detail.css'%}"}>
<div class = "card-wrapper mt-5 m-3 bottom">
  <div class = "cardd">
    <!-- card left -->
    <div class = "product-imgs">
      <div class = "img-display">
        <div class = "img-showcase">



          <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for picture in product.productimage_set.all  %}
                        {% if picture == product.productimage_set.all.first %}
                        <div class="carousel-item active thumbnail shadow-sm ">
                            <img class="" src="{{picture.image.url}}" alt="">
                        </div>
                        {% else %}
                        <div class="carousel-item thumbnail shadow-sm">
                            <img class="shoe image d-block w-100 " width="400" height="270" src="{{picture.image.url}}" alt="">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
              </div>
            </div>




        </div>
      </div>

    </div>



	<div class="product-price mb-0">
		<!--
		<p class="last-price">Old Price: <span>$257.00</span></p>-->
		<p> китептин аты:<span>{{product.title}}</span></p>
		{% if product.price == none%}
		<p>басы: <span>бекер</span></p>
		{%else%}
		<p>басы: <span>${{product.price}}</span></p>
		{%endif%}

		<p>китептин авторуу: <span>${{product.book_author}}</span></p>
		<p>китеп жазылган тили <span>{{product.language}}</span></p>
		<p> китеп жонундо малымат<span>{{product.description|safe}}</span></p>
	<div class="purchase-inf mb-0">
		{% if product.pdf %}
		 <a href="{{ product.pdf.url }}" class="btn btn-primary mb-2" target="_blank">
              китепти жуктоп алуу <i class="fas fa-download"></i>
            </a>
		{% endif%}
		<button class=" collapsed btn btn-info mb-3 me-3" type="button" data-bs-toggle="collapse"
			data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree"
		>комментарийлер: {{comment_count}}
		</button>
		{% if request.user == product.author %}
		<a class= "btn btn-info mb-3" href="{% url 'main:update' product.id%}">тузотуу</a>
		{% endif %}

	</div>


</div>
<form action="{% url 'main:comment_new' product.id %}" method="post" class="input-group">{% csrf_token%}
          <input class="form-control" name="body" type="text" placeholder="Type your comment..." aria-describedby="'button-addon" >
          <button class="btn btn-outline-success" type="submit" id="button-addon"><i class="bi bi-send-plus"></i></button>
      </form>
</div>

<div class="accordion-item mb-3 m-4">

		<div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
			data-bs-parent="#accordionExample">
			<div class="accordion-body">

				{% for comment in comments %}
				<div class="card mt-3">


					<div class=" card-body">

						<div class="w-100">
							<div class="d-flex justify-content-between align-items-center mb-3">
								<h6 class="text-primary fw-bold mb-0">
									<a href="{% url 'users:profile' comment.author  %}">@{{comment.author}}</a>
									 </h6>
										<p class="mb-0">{{comment.date}}</p>
							</div>

							<div data-expandable>
								<p>{{comment.body}} </p>

								<div class="d-flex justify-content-between align-items-center mt-3">
									<div class="d-flex align-items-center">

										  <form action="{% url 'main:like_comment' %}" method="POST" class='like-form' id='{{comment.id}}'>
                                {% csrf_token %}

                                <input type="hidden" name="post_id" value={{comment.id}}>
                                    <button type="submit" class="btn btn-outline-success btn-sm like-btn{{comment.id}}">
                                        {% if user not in comment.liked.all %}
                                            Like
                                        {% else %}
                                            Unlike
                                        {% endif %}
                                    </button>
                                     <strong class="like-count{{comment.id}} me-5">{{comment.num_likes}}</strong>

                            </form>
										{% if request.user == comment.author %}
											<small><a class="me-5" href="{% url 'main:comment_delete' product.id comment.id   %}"><i class=" bi bi-trash3"></i></a></small>
										{% endif %}
									</div>

								</div>

							</div>

						</div>

					</div>
				</div>

				{% endfor%}
			</div>
		</div>
	</div>
{% if product.category%}
<div class="container-fluid bg-trasparent my-4 p-3" style="position: relative">
	<div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
        {% for i in product.category.product_set.all %}
        {% if product != i %}
		<div class="col hp">
			<div class="card h-100 shadow-sm">
				<a href="{% url 'main:detail' product.id %}">

					<img src="{{i.productimage_set.all.first.image.url}}" class="card-img-top" alt="product.title" />
				</a>

				<div class="label-top shadow-sm">
					<a class="text-white" href="{% url 'main:detail' product.id %}"">{{i.category}}</a>
				</div>
				<div class="card-body">
					<div class="clearfix mb-3">
						<span class="float-start badge rounded-pill bg-success">{{i.price}} com</span>
						 {% if i.book_author %}
                            <span class="float-end"><a href="#"
                                    class="small text-muted text-uppercase aff-link">author: {{i.book_author}}</a>
                            </span>
                             {% endif%}
					</div>
					<h6 class="card-title">
						<a href="{% url 'main:detail' product.id %}" class="title">{{i.title}}</a>
					</h6>
					<div class="clearfix mb-1">
							<a href="{% url 'users:addremovesaved' i.id %}"><i class="bi bi-bookmark-fill"></i></a>
                            <!--<span class="float-start"><a href="#"><i class="fas fa-question-circle"></i></a></span>-->

                            <span class="float-end">
								 <form action="{% url 'main:like-store' %}" method="POST" class='like-form' id='{{i.id}}'>
                                {% csrf_token %}

                                <input type="hidden" name="post_id" value={{i.id}}>
                                    <button type="submit" class="btn btn-outline-success btn-sm like-btn{{i.id}}">
                                        {% if user not in i.liked.all %}
                                            Like
                                        {% else %}
                                            Unlike
                                        {% endif %}
                                    </button>
                                     <strong class="like-count{{i.id}} me-3">{{i.num_likes}}</strong>

                            </form>

                            </span>
                        </div>
				</div>
			</div>
		</div>
        {% endif %}
		{% endfor %}
	</div>
</div>

{%endif%}


<script>const imgs = document.querySelectorAll('.img-select a');
const imgBtns = [...imgs];
let imgId = 1;

imgBtns.forEach((imgItem) => {
    imgItem.addEventListener('click', (event) => {
        event.preventDefault();
        imgId = imgItem.dataset.id;
        slideImage();
    });
});

function slideImage(){
    const displayWidth = document.querySelector('.img-showcase img:first-child').clientWidth;

    document.querySelector('.img-showcase').style.transform = `translateX(${- (imgId - 1) * displayWidth}px)`;
}

window.addEventListener('resize', slideImage);</script>

<script src="{% static 'js/like_button.js'%}"></script>
{% endblock content %}

templates/store/product_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="container bottom">
    <div class="row">
        <div class="col"></div>
        <div class="col-10 mt-5 ">
             <div class="row">
               <h2 class="col-10">New Post</h2>
            <button type="button" class="btn btn-info col-2" data-bs-toggle="modal" data-bs-target="#storeadd">
                      <i class="bi bi-question-lg"></i>
            </button>
           </div>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{form|crispy}}

                    <button type="submit" class="btn btn-primary me-5" >сактоо</button>
                <a class="btn btn-secondary" href="{% url 'main:shop'%}"> артка кайтуу</a>

            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/store/product_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
  <div class="container top bottom">
    <div class="row">
        <div class="col"></div>
        <div class="col-sm-12 col-md-12 col-lg-6 mt-5 mb-5 ">
            <h2>Update Product </h2>
            <form  method="post" enctype="multipart/form-data" >{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
                <a class="btn btn-danger" href="{% url 'main:delete' pr.id  %}"> Delete</a>
                <a class="btn btn-secondary" href="{% url 'main:detail' pr.id  %}"> Back Detail</a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/store/recently_viewed.html
{% extends "base.html" %}

{% block content %}
   <!-- Product Cart Start -->
   <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" > Recently Viewed Products</h4>
        <div class="d-flex flex-wrap justify-content-between">
         <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
       {% for i in products %}
        {% if product != i %}
		<div class="col hp">
			<div class="card h-100 shadow-sm">
				<a href="#">

					<img src="{{i.productimage_set.all.first.image.url}}" class="card-img-top" alt="product.title" />
				</a>

				<div class="label-top shadow-sm">
					<a class="text-white" href="#">{{i.category}}</a>
				</div>
				<div class="card-body">
					<div class="clearfix mb-3">
						<span class="float-start badge rounded-pill bg-success">{{i.price}} com</span>
						 {% if i.book_author %}
                            <span class="float-end"><a href="#"
                                    class="small text-muted text-uppercase aff-link">author: {{i.book_author}}</a>
                            </span>
                             {% endif%}
					</div>
					<h6 class="card-title">
						<a href="{% url 'main:detail' i.id %}" class="title">{{i.title}}</a>
					</h6>
				</div>
			</div>
		</div>
        {% endif %}
		{% endfor %}
	</div>

        </div>
    </div>
</div>
<!-- Product Cart End -->
{% endblock content %}

templates/store/store.html
{% extends 'base.html'%}
{% load static %}
{% load grouptags%}
{% block content %}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
      xmlns="http://www.w3.org/1999/html">
<link rel="stylesheet" href="{%static 'css/store.css'%}"}>


<style>@media (min-width: 769px) and (max-width: 1400px) {.top{ margin-top:6rem !important; }
</style>

    <div class="container-fluid bg-trasparent top bottom my-4 p-3 mb-5" style="position: relative">
        <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-4 g-3">
			{% for i in products%}
            <div class="col hp">
                <div class="card h-100 shadow-sm">
                    <a href="{% url 'main:detail' i.id%}">
						{% if i.productimage_set.exists %}
                        <img src="{{i.productimage_set.all.first.image.url}}" class="card-img-top"
                            alt="product.title" />
						{% else%}
						<img src="{{i.image.url}}">
						{% endif%}
                    </a>

                    <div class="label-top shadow-sm">
                        <a class="text-white" href="#">{{i.category}}</a>
                    </div>
                     <div class="label-top-left shadow-sm">
                        <a class="text-white" href="#">тили:{{i.language}}</a>
                    </div>
                    <div class="card-body">
                        <div class="clearfix mb-3">
                            {% if i.price == none %}
                            <span class="float-start badge rounded-pill bg-success"> бекер</span>
                            {% else%}
                            <span class="float-start badge rounded-pill bg-success">{{i.price}}</span> com
                            {% endif%}
                              {% if i.book_author %}
                            <span class="float-end"><a href="#"
                                    class="small text-muted text-uppercase aff-link">автор: {{i.book_author}}</a>
                            </span>
                             {% endif%}
                        </div>
                        <h6 class="card-title mb-4">
                           <a href="{% url 'main:detail' i.id%}" class="title text-success fw-bold">{{i.title}}</a>
                        </h6>

                        <div class="clearfix mb-1">
                            {% if request.user == i.author %}
                              {% else%}

                                         <a href="{% url 'users:addremovesaved' i.id %}" class="me-3" >
                                          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                                              <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                                            </svg>
                                         </a>
                            {% endif%}
                            <a class="mr-5 btn btn-primary btn-sm">comments: <i class="bi bi-chat-text"></i> {{i.comments.count}}</a>
                            <span class="float-end">
                                 <form action="{% url 'main:like-store' %}" method="POST" class='like-form' id='{{i.id}}'>
                                {% csrf_token %}

                                <input type="hidden" name="post_id" value={{i.id}}>
                                    <button type="submit" class="btn btn-outline-success btn-sm like-btn{{i.id}}">
                                        {% if user not in i.liked.all %}
                                            Like
                                        {% else %}
                                            Unlike
                                        {% endif %}
                                    </button>
                                     <strong class="like-count{{i.id}} me-3">{{i.num_likes}}</strong>

                            </form>

                            </span>
                        </div>
                    </div>
                </div>
            </div>
			{% endfor %}

        </div>
    </div>
                  {% if request.user|in_group:'shopadd'%}
                 {% include 'include/add_button.html'%}
{% endif%}
{% include 'include/add_button.html'%}

<script src="{% static 'js/like_button.js'%}"></script>


  {% endblock content %}